### ISSUE TITLE
Can not find profiles

### ISSUE THREAD

**Issue by Jcarcinogen** [karelrooted/resignipa#1]
I have 2 Apple TV's so I use 2 different provisioning profiles with a dash (ex:  com.scott.kodi-bed). I am getting the following error:

`scott@Scotts-Mac-mini resignipa-main % bash <(curl -L -s https://raw.githubusercontent.com/karelrooted/resignipa/main/resignipa.sh) -i /Users/scott/kodi/kodi-bed/org.xbmc.kodi-tvos_20.2-tvos.ipa -s "Apple Development: sxxxxxxx@me.com (NXXXXXXXXX)" -p "tvOS Team Provisioning Profile: com.scott.kodi-bed" -d AppleTV-bedroom

bash: yq: command not found
bash: yq: command not found
Profile does not exist. Please try again.`

**Comment by karelrooted** [comment]
> I have 2 Apple TV's so I use 2 different provisioning profiles with a dash (ex:  com.scott.kodi-bed). I am getting the following error:
> 
> 
> 
> `scott@Scotts-Mac-mini resignipa-main % bash <(curl -L -s https://raw.githubusercontent.com/karelrooted/resignipa/main/resignipa.sh) -i /Users/scott/kodi/kodi-bed/org.xbmc.kodi-tvos_20.2-tvos.ipa -s "Apple Development: sxxxxxxx@me.com (NXXXXXXXXX)" -p "tvOS Team Provisioning Profile: com.scott.kodi-bed" -d AppleTV-bedroom
> 
> 
> 
> bash: yq: command not found
> 
> bash: yq: command not found
> 
> Profile does not exist. Please try again.`

the script use yq command to filter profile from profile list, you can try running "brew install yq " in terminal
and check the result, may be something is wrong with your local brew environment

Todo: the script need to check brew install result

**Comment by Jcarcinogen** [comment]
Yep, just neeed to install yq and it worked. Nice script.

**Comment by karelrooted** [comment]
You install it and the “brew install yq” just works?, the script has built
in check for yq command and install it with brew if not found automatically, it seems weird your install command works but the script failed

**Comment by Jcarcinogen** [comment]
I ran "brew install yq" (I had a brew environment already) and then the 
"bash <(curl -L -s https://raw.githubusercontent.com/karelrooted/resignipa/main/resignipa.sh) -i /Users/scott/kodi/kodi-bed/org.xbmc.kodi-tvos_20.2-tvos.ipa -s "Apple Development: [sxxxxxxx@me.com](mailto:sxxxxxxx@me.com) (NXXXXXXXXX)" -p "tvOS Team Provisioning Profile: com.scott.kodi-bed" -d AppleTV-bedroom"
command worked. I'm not familiar with yq.

**Comment by karelrooted** [comment]
the script is updated with checking brew install result and with a message for user to manual install yq if failed
